title: Majed Alfaraj
description: Majed Alfaraj is an EECS senior at UC Berkeley interested in machine learning, systems, and security.
url: https://majedalfaraj.github.io
baseurl: ""
lang: en

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/og.png

plugins:
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
  - .claude
