title: Majed AlFaraj
description: Majed AlFaraj is an EECS student at UC Berkeley interested in machine learning and cybersecurity.
url: https://majedalfaraj.github.io
baseurl: ""
lang: en

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
  - .claude
